[package]
name = "spansy"
version = "0.1.0"
edition = "2021"
description = "Parsing with span information"
repository = "https://github.com/sinui0/spansy"
license = "MIT OR Apache-2.0"

[dependencies]
httparse = "1"
pest = "2"
pest_derive = "2"
thiserror = "1"

